// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Character
    {
        [DataMember(Name = "EntityId")]
        public uint EntityId;
        [DataMember(Name = "PlayerId")]
        public uint PlayerId;
        [DataMember(Name = "Health")]
        public float Health;

        public Character(
            uint EntityId,
            uint PlayerId,
            float Health
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Health = Health;
        }

        public Character()
        {
        }
    }
}
