// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ColorSpellAction
    {
        [DataMember(Name = "ActionId")]
        public uint ActionId;
        [DataMember(Name = "CasterCharacterId")]
        public uint CasterCharacterId;
        [DataMember(Name = "TargetCharacterId")]
        public uint TargetCharacterId;
        [DataMember(Name = "SpellType")]
        public ColorSpellType SpellType;

        public ColorSpellAction(
            uint ActionId,
            uint CasterCharacterId,
            uint TargetCharacterId,
            ColorSpellType SpellType
        )
        {
            this.ActionId = ActionId;
            this.CasterCharacterId = CasterCharacterId;
            this.TargetCharacterId = TargetCharacterId;
            this.SpellType = SpellType;
        }

        public ColorSpellAction()
        {
            this.SpellType = new();
        }
    }
}
