// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ColorSpellState
    {
        [DataMember(Name = "ActionId")]
        public uint ActionId;
        [DataMember(Name = "SpellStep")]
        public int SpellStep;

        public ColorSpellState(
            uint ActionId,
            int SpellStep
        )
        {
            this.ActionId = ActionId;
            this.SpellStep = SpellStep;
        }

        public ColorSpellState()
        {
        }
    }
}
