// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MovementAction
    {
        [DataMember(Name = "ActionId")]
        public uint ActionId;
        [DataMember(Name = "PlayerId")]
        public uint PlayerId;
        [DataMember(Name = "Destination")]
        public DbVector2 Destination;

        public MovementAction(
            uint ActionId,
            uint PlayerId,
            DbVector2 Destination
        )
        {
            this.ActionId = ActionId;
            this.PlayerId = PlayerId;
            this.Destination = Destination;
        }

        public MovementAction()
        {
            this.Destination = new();
        }
    }
}
