// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Npc
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "npc_id")]
        public uint NpcId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;

        public Npc(
            uint EntityId,
            uint NpcId,
            uint PlayerId
        )
        {
            this.EntityId = EntityId;
            this.NpcId = NpcId;
            this.PlayerId = PlayerId;
        }

        public Npc()
        {
        }
    }
}
