// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tick
    {
        [DataMember(Name = "ScheduledId")]
        public ulong ScheduledId;
        [DataMember(Name = "ScheduleAt")]
        public SpacetimeDB.ScheduleAt ScheduleAt;
        [DataMember(Name = "EndTime")]
        public SpacetimeDB.Timestamp EndTime;

        public Tick(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduleAt,
            SpacetimeDB.Timestamp EndTime
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduleAt = ScheduleAt;
            this.EndTime = EndTime;
        }

        public Tick()
        {
            this.ScheduleAt = null!;
        }
    }
}
