// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyColorSpellHandler(ReducerEventContext ctx, ColorSpellAction action);
        public event ApplyColorSpellHandler? OnApplyColorSpell;

        public void ApplyColorSpell(ColorSpellAction action)
        {
            conn.InternalCallReducer(new Reducer.ApplyColorSpell(action), this.SetCallReducerFlags.ApplyColorSpellFlags);
        }

        public bool InvokeApplyColorSpell(ReducerEventContext ctx, Reducer.ApplyColorSpell args)
        {
            if (OnApplyColorSpell == null) return false;
            OnApplyColorSpell(
                ctx,
                args.Action
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyColorSpell : Reducer, IReducerArgs
        {
            [DataMember(Name = "action")]
            public ColorSpellAction Action;

            public ApplyColorSpell(ColorSpellAction Action)
            {
                this.Action = Action;
            }

            public ApplyColorSpell()
            {
                this.Action = new();
            }

            string IReducerArgs.ReducerName => "ApplyColorSpell";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ApplyColorSpellFlags;
        public void ApplyColorSpell(CallReducerFlags flags) => ApplyColorSpellFlags = flags;
    }
}
