// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateColorSpellActionHandler(ReducerEventContext ctx, string color, string length, string targetName);
        public event CreateColorSpellActionHandler? OnCreateColorSpellAction;

        public void CreateColorSpellAction(string color, string length, string targetName)
        {
            conn.InternalCallReducer(new Reducer.CreateColorSpellAction(color, length, targetName), this.SetCallReducerFlags.CreateColorSpellActionFlags);
        }

        public bool InvokeCreateColorSpellAction(ReducerEventContext ctx, Reducer.CreateColorSpellAction args)
        {
            if (OnCreateColorSpellAction == null) return false;
            OnCreateColorSpellAction(
                ctx,
                args.Color,
                args.Length,
                args.TargetName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateColorSpellAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "color")]
            public string Color;
            [DataMember(Name = "length")]
            public string Length;
            [DataMember(Name = "targetName")]
            public string TargetName;

            public CreateColorSpellAction(
                string Color,
                string Length,
                string TargetName
            )
            {
                this.Color = Color;
                this.Length = Length;
                this.TargetName = TargetName;
            }

            public CreateColorSpellAction()
            {
                this.Color = "";
                this.Length = "";
                this.TargetName = "";
            }

            string IReducerArgs.ReducerName => "CreateColorSpellAction";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateColorSpellActionFlags;
        public void CreateColorSpellAction(CallReducerFlags flags) => CreateColorSpellActionFlags = flags;
    }
}
