// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateMovementActionHandler(ReducerEventContext ctx, int x, int y);
        public event CreateMovementActionHandler? OnCreateMovementAction;

        public void CreateMovementAction(int x, int y)
        {
            conn.InternalCallReducer(new Reducer.CreateMovementAction(x, y), this.SetCallReducerFlags.CreateMovementActionFlags);
        }

        public bool InvokeCreateMovementAction(ReducerEventContext ctx, Reducer.CreateMovementAction args)
        {
            if (OnCreateMovementAction == null) return false;
            OnCreateMovementAction(
                ctx,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateMovementAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "y")]
            public int Y;

            public CreateMovementAction(
                int X,
                int Y
            )
            {
                this.X = X;
                this.Y = Y;
            }

            public CreateMovementAction()
            {
            }

            string IReducerArgs.ReducerName => "CreateMovementAction";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateMovementActionFlags;
        public void CreateMovementAction(CallReducerFlags flags) => CreateMovementActionFlags = flags;
    }
}
