// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateDummyPlayerHandler(ReducerEventContext ctx, int x, int y);
        public event CreateDummyPlayerHandler? OnCreateDummyPlayer;

        public void CreateDummyPlayer(int x, int y)
        {
            conn.InternalCallReducer(new Reducer.CreateDummyPlayer(x, y), this.SetCallReducerFlags.CreateDummyPlayerFlags);
        }

        public bool InvokeCreateDummyPlayer(ReducerEventContext ctx, Reducer.CreateDummyPlayer args)
        {
            if (OnCreateDummyPlayer == null) return false;
            OnCreateDummyPlayer(
                ctx,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateDummyPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "y")]
            public int Y;

            public CreateDummyPlayer(
                int X,
                int Y
            )
            {
                this.X = X;
                this.Y = Y;
            }

            public CreateDummyPlayer()
            {
            }

            string IReducerArgs.ReducerName => "CreateDummyPlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateDummyPlayerFlags;
        public void CreateDummyPlayer(CallReducerFlags flags) => CreateDummyPlayerFlags = flags;
    }
}
