// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateDummyPlayerHandler(ReducerEventContext ctx);
        public event CreateDummyPlayerHandler? OnCreateDummyPlayer;

        public void CreateDummyPlayer()
        {
            conn.InternalCallReducer(new Reducer.CreateDummyPlayer(), this.SetCallReducerFlags.CreateDummyPlayerFlags);
        }

        public bool InvokeCreateDummyPlayer(ReducerEventContext ctx, Reducer.CreateDummyPlayer args)
        {
            if (OnCreateDummyPlayer == null) return false;
            OnCreateDummyPlayer(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateDummyPlayer : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "CreateDummyPlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateDummyPlayerFlags;
        public void CreateDummyPlayer(CallReducerFlags flags) => CreateDummyPlayerFlags = flags;
    }
}
