// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DoConnectHandler(ReducerEventContext ctx);
        public event DoConnectHandler? OnDoConnect;

        public void DoConnect()
        {
            conn.InternalCallReducer(new Reducer.DoConnect(), this.SetCallReducerFlags.DoConnectFlags);
        }

        public bool InvokeDoConnect(ReducerEventContext ctx, Reducer.DoConnect args)
        {
            if (OnDoConnect == null) return false;
            OnDoConnect(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DoConnect : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "DoConnect";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DoConnectFlags;
        public void DoConnect(CallReducerFlags flags) => DoConnectFlags = flags;
    }
}
