// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DoColorSpellActionHandler(ReducerEventContext ctx, ColorSpellAction action);
        public event DoColorSpellActionHandler? OnDoColorSpellAction;

        public void DoColorSpellAction(ColorSpellAction action)
        {
            conn.InternalCallReducer(new Reducer.DoColorSpellAction(action), this.SetCallReducerFlags.DoColorSpellActionFlags);
        }

        public bool InvokeDoColorSpellAction(ReducerEventContext ctx, Reducer.DoColorSpellAction args)
        {
            if (OnDoColorSpellAction == null) return false;
            OnDoColorSpellAction(
                ctx,
                args.Action
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DoColorSpellAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "action")]
            public ColorSpellAction Action;

            public DoColorSpellAction(ColorSpellAction Action)
            {
                this.Action = Action;
            }

            public DoColorSpellAction()
            {
                this.Action = new();
            }

            string IReducerArgs.ReducerName => "DoColorSpellAction";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DoColorSpellActionFlags;
        public void DoColorSpellAction(CallReducerFlags flags) => DoColorSpellActionFlags = flags;
    }
}
