// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DoDisconnectHandler(ReducerEventContext ctx);
        public event DoDisconnectHandler? OnDoDisconnect;

        public void DoDisconnect()
        {
            conn.InternalCallReducer(new Reducer.DoDisconnect(), this.SetCallReducerFlags.DoDisconnectFlags);
        }

        public bool InvokeDoDisconnect(ReducerEventContext ctx, Reducer.DoDisconnect args)
        {
            if (OnDoDisconnect == null) return false;
            OnDoDisconnect(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DoDisconnect : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "DoDisconnect";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DoDisconnectFlags;
        public void DoDisconnect(CallReducerFlags flags) => DoDisconnectFlags = flags;
    }
}
