// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DoMovementActionHandler(ReducerEventContext ctx, MovementAction movementAction);
        public event DoMovementActionHandler? OnDoMovementAction;

        public void DoMovementAction(MovementAction movementAction)
        {
            conn.InternalCallReducer(new Reducer.DoMovementAction(movementAction), this.SetCallReducerFlags.DoMovementActionFlags);
        }

        public bool InvokeDoMovementAction(ReducerEventContext ctx, Reducer.DoMovementAction args)
        {
            if (OnDoMovementAction == null) return false;
            OnDoMovementAction(
                ctx,
                args.MovementAction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DoMovementAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "movementAction")]
            public MovementAction MovementAction;

            public DoMovementAction(MovementAction MovementAction)
            {
                this.MovementAction = MovementAction;
            }

            public DoMovementAction()
            {
                this.MovementAction = new();
            }

            string IReducerArgs.ReducerName => "DoMovementAction";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DoMovementActionFlags;
        public void DoMovementAction(CallReducerFlags flags) => DoMovementActionFlags = flags;
    }
}
