// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndTickHandler(ReducerEventContext ctx, Tick tick);
        public event EndTickHandler? OnEndTick;

        public void EndTick(Tick tick)
        {
            conn.InternalCallReducer(new Reducer.EndTick(tick), this.SetCallReducerFlags.EndTickFlags);
        }

        public bool InvokeEndTick(ReducerEventContext ctx, Reducer.EndTick args)
        {
            if (OnEndTick == null) return false;
            OnEndTick(
                ctx,
                args.Tick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndTick : Reducer, IReducerArgs
        {
            [DataMember(Name = "tick")]
            public Tick Tick;

            public EndTick(Tick Tick)
            {
                this.Tick = Tick;
            }

            public EndTick()
            {
                this.Tick = new();
            }

            string IReducerArgs.ReducerName => "EndTick";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EndTickFlags;
        public void EndTick(CallReducerFlags flags) => EndTickFlags = flags;
    }
}
