// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestSingleHandler(ReducerEventContext ctx, string targetName);
        public event TestSingleHandler? OnTestSingle;

        public void TestSingle(string targetName)
        {
            conn.InternalCallReducer(new Reducer.TestSingle(targetName), this.SetCallReducerFlags.TestSingleFlags);
        }

        public bool InvokeTestSingle(ReducerEventContext ctx, Reducer.TestSingle args)
        {
            if (OnTestSingle == null) return false;
            OnTestSingle(
                ctx,
                args.TargetName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestSingle : Reducer, IReducerArgs
        {
            [DataMember(Name = "targetName")]
            public string TargetName;

            public TestSingle(string TargetName)
            {
                this.TargetName = TargetName;
            }

            public TestSingle()
            {
                this.TargetName = "";
            }

            string IReducerArgs.ReducerName => "TestSingle";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestSingleFlags;
        public void TestSingle(CallReducerFlags flags) => TestSingleFlags = flags;
    }
}
