// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestUpdateHandler(ReducerEventContext ctx, string name);
        public event TestUpdateHandler? OnTestUpdate;

        public void TestUpdate(string name)
        {
            conn.InternalCallReducer(new Reducer.TestUpdate(name), this.SetCallReducerFlags.TestUpdateFlags);
        }

        public bool InvokeTestUpdate(ReducerEventContext ctx, Reducer.TestUpdate args)
        {
            if (OnTestUpdate == null) return false;
            OnTestUpdate(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestUpdate : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public TestUpdate(string Name)
            {
                this.Name = Name;
            }

            public TestUpdate()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "TestUpdate";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestUpdateFlags;
        public void TestUpdate(CallReducerFlags flags) => TestUpdateFlags = flags;
    }
}
