// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ColorSpellActionHandle : RemoteTableHandle<EventContext, ColorSpellAction>
        {
            protected override string RemoteTableName => "Color_spell_action";

            public sealed class ActionIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ColorSpellAction row) => row.ActionId;

                public ActionIdUniqueIndex(ColorSpellActionHandle table) : base(table) { }
            }

            public readonly ActionIdUniqueIndex ActionId;

            internal ColorSpellActionHandle(DbConnection conn) : base(conn)
            {
                ActionId = new(this);
            }

            protected override object GetPrimaryKey(ColorSpellAction row) => row.ActionId;
        }

        public readonly ColorSpellActionHandle ColorSpellAction;
    }
}
