// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MovementActionHandle : RemoteTableHandle<EventContext, MovementAction>
        {
            protected override string RemoteTableName => "movement_action";

            public sealed class ActionIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MovementAction row) => row.ActionId;

                public ActionIdUniqueIndex(MovementActionHandle table) : base(table) { }
            }

            public readonly ActionIdUniqueIndex ActionId;

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MovementAction row) => row.PlayerId;

                public PlayerIdUniqueIndex(MovementActionHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal MovementActionHandle(DbConnection conn) : base(conn)
            {
                ActionId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(MovementAction row) => row.ActionId;
        }

        public readonly MovementActionHandle MovementAction;
    }
}
