// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcHandle : RemoteTableHandle<EventContext, Npc>
        {
            protected override string RemoteTableName => "npc";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Npc row) => row.EntityId;

                public EntityIdUniqueIndex(NpcHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class NpcIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Npc row) => row.NpcId;

                public NpcIdIndex(NpcHandle table) : base(table) { }
            }

            public readonly NpcIdIndex NpcId;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Npc row) => row.PlayerId;

                public PlayerIdIndex(NpcHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal NpcHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                NpcId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Npc row) => row.EntityId;
        }

        public readonly NpcHandle Npc;
    }
}
